# A simple configuration properties, is the same as contrib.sink.avro.neo4j.json
name=Neo4jSinkConnector
topics=datalake
connector.class=streams.kafka.connect.sink.Neo4jSinkConnector
key.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=false
value.converter=org.apache.kafka.connect.json.JsonConverter
value.converter.schemas.enable=false
errors.retry.timeout=-1
errors.retry.delay.max.ms=1000
errors.tolerance=all
errors.log.enable=true
errors.log.include.messages=false
neo4j.server.uri=bolt://127.0.0.1:7687
neo4j.authentication.basic.username=neo4j
neo4j.authentication.basic.password=password
neo4j.encryption.enabled=false
neo4j.topic.cud=graphlake
