#!/usr/sbin/nft -f

flush ruleset

table inet filter {
    set anthropic_v4 {
        type ipv4_addr
        flags interval
        elements = { 160.79.104.0/21 }
    }

    set anthropic_v6 {
        type ipv6_addr
        flags interval
        elements = { 2607:6bc0::/48 }
    }

    chain input {
        type filter hook input priority 0; policy drop;
        iif lo accept
        ct state established,related accept
    }

    chain forward {
        type filter hook forward priority 0; policy drop;
    }

    chain output {
        type filter hook output priority 0; policy drop;

        oif lo accept
        ct state established,related accept

        # DNS - needed to resolve anthropic.com hostnames
        udp dport 53 accept
        tcp dport 53 accept

        ip daddr @anthropic_v4 accept
        ip6 daddr @anthropic_v6 accept
    }
}